// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "Returns hello message",
                "produces": [
                    "text/plain"
                ],
                "summary": "Root endpoint",
                "responses": {
                    "200": {
                        "description": "Hello, Maelstrom!",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/greet": {
            "post": {
                "description": "Greet user by name",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "api"
                ],
                "summary": "Greet user",
                "parameters": [
                    {
                        "description": "User name",
                        "name": "name",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.Request"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "greeting",
                        "schema": {
                            "$ref": "#/definitions/v1.Response"
                        }
                    },
                    "400": {
                        "description": "Invalid JSON",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "405": {
                        "description": "Method not allowed",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/import/{filename}": {
            "post": {
                "description": "Manual import",
                "produces": [
                    "application/json"
                ],
                "summary": "Import YAML",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filename",
                        "name": "filename",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/raw-yamls": {
            "get": {
                "description": "List registry raw contents (unrendered)",
                "produces": [
                    "application/json"
                ],
                "summary": "List Raw YAMLs",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/registry.RawYAML"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/yamls": {
            "get": {
                "description": "List registry",
                "produces": [
                    "application/json"
                ],
                "summary": "List YAMLs",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/registry.YAMLImport"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "registry.RawYAML": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "raw": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "registry.YAMLImport": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "content": {
                    "type": "object",
                    "additionalProperties": true
                },
                "filename": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "v1.Request": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "v1.Response": {
            "type": "object",
            "properties": {
                "greeting": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Maelstrom API",
	Description:      "Minimal Go HTTP server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
